# Generated by Django 5.2.5 on 2025-08-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
